title: Ryan Swope
url: "https://rggs.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./villanova.jpg"
favicon: "./public/favicon.ico"

tracking_id: G-23B5LGK2G6

footer: yes
footer_url: "https://github.com/rggs"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Resume"
   link: "/resume"
 - name: "Projects"
   link: "/projects"
 - name: "Contact"
   link: "contact"
 - name: "GitHub"
   link: "https://github.com/rggs"
